services:
  ########################################################################################
  # Nuxt + FastAPI together in a single service
  # (because VS Code does not support single workspace for multiple containers)
  ########################################################################################
  app:
    image: "python:3.13.3-bookworm" # Node is installed wih a container "feature" then
    environment:
      - PYTHONPATH=/workspaces/fast-batteries/back
      - PYTHONUNBUFFERED=1
      - PYTHONBREAKPOINT=ipdb.set_trace
    volumes:
      - ..:/workspaces:delegated # Performance optimization option for the volume.
    command: sleep infinity # Things don't shut down after the process ends.
    ports:
      - "3000:3000" # Nuxt
      - "8000:8000" # FastAPI

  ########################################################################################
  # PostgreSQL service
  ########################################################################################
  pg:
    image: "postgres:17-bookworm"
    environment:
      - POSTGRES_DB=localdb
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpassword
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data

  ########################################################################################
  # pgAdmin service
  ########################################################################################
  pgadmin:
    image: "dpage/pgadmin4:9.2"
    environment:
      - PGADMIN_DEFAULT_EMAIL=localuser@fast-batteries.w3lt.org
      - PGADMIN_DEFAULT_PASSWORD=localpassword
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - pg
    ports:
      - "8180:80"

  ########################################################################################
  # CloudBeaver service
  ########################################################################################
  dbeaver:
    image: "dbeaver/cloudbeaver:latest"
    restart: unless-stopped
    volumes:
      - dbeaver-data:/opt/cloudbeaver/workspace
    depends_on:
      - pg
    ports:
      - "8978:8978"

  ########################################################################################
  # Redis service
  ########################################################################################
  redis:
    image: "redis:7-bookworm"
    restart: unless-stopped
    volumes:
      - redis-data:/data
  ########################################################################################
  # Redis Insight service
  ########################################################################################
  redisinsight:
    image: "redis/redisinsight:latest"
    restart: unless-stopped
    ports:
      - "5540:5540"
  ########################################################################################
  # MinIO service
  ########################################################################################
  minio:
    image: minio/minio:RELEASE.2025-04-03T14-56-28Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=localuser
      - MINIO_ROOT_PASSWORD=localpassword
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    volumes:
      - minio-data:/data
    restart: unless-stopped

volumes:
  pg-data:
  pgadmin-data:
  dbeaver-data:
  redis-data:
  minio-data:
